# Generated by Django 4.2.5 on 2023-09-08 00:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 533290))),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_plazo', models.DateTimeField(default=datetime.datetime(2023, 9, 12, 21, 15, 32, 533290))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo_detalle',
            fields=[
                ('id_prestamo_detalle', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventario')),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestamos.prestamo')),
            ],
        ),
    ]
