// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestion_inventario.Models;

#nullable disable

namespace gestion_inventario.Migrations
{
    [DbContext(typeof(DbContextInventario))]
    partial class DbContextInventarioModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gestion_inventario.Models.Bodega", b =>
                {
                    b.Property<int>("id_bodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_bodega"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.HasKey("id_bodega");

                    b.ToTable("bodegas");
                });

            modelBuilder.Entity("gestion_inventario.Models.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_categoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("gestion_inventario.Models.HistoricoMovimiento", b =>
                {
                    b.Property<int>("id_movimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_movimiento"));

                    b.Property<string>("comentarios")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_inventario")
                        .HasColumnType("int");

                    b.Property<int>("id_tipo_movimiento")
                        .HasColumnType("int");

                    b.Property<long>("inventarioNavigationid_inventario")
                        .HasColumnType("bigint");

                    b.Property<int>("movimientoTipoNavigationid_movimiento_tipo")
                        .HasColumnType("int");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_movimiento");

                    b.HasIndex("inventarioNavigationid_inventario");

                    b.HasIndex("movimientoTipoNavigationid_movimiento_tipo");

                    b.ToTable("historico_movimientos");
                });

            modelBuilder.Entity("gestion_inventario.Models.Inventario", b =>
                {
                    b.Property<long?>("id_inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("id_inventario"));

                    b.Property<int>("InventarioEstadoNavigationid_inventario_estado")
                        .HasColumnType("int");

                    b.Property<int>("bodega")
                        .HasColumnType("int");

                    b.Property<int>("bodegaNavigationid_bodega")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_inventario_estado")
                        .HasColumnType("int");

                    b.Property<int?>("id_producto")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("productoNavigationid_producto")
                        .HasColumnType("int");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_inventario");

                    b.HasIndex("InventarioEstadoNavigationid_inventario_estado");

                    b.HasIndex("bodegaNavigationid_bodega");

                    b.HasIndex("productoNavigationid_producto");

                    b.ToTable("inventario");
                });

            modelBuilder.Entity("gestion_inventario.Models.InventarioEstado", b =>
                {
                    b.Property<int>("id_inventario_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_inventario_estado"));

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_estado_inventario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_inventario_estado");

                    b.ToTable("inventario_estados");
                });

            modelBuilder.Entity("gestion_inventario.Models.MovimientoTipo", b =>
                {
                    b.Property<int>("id_movimiento_tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_movimiento_tipo"));

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_movimiento_tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_movimiento_tipo");

                    b.ToTable("movimiento_tipos");
                });

            modelBuilder.Entity("gestion_inventario.Models.Persona", b =>
                {
                    b.Property<long>("id_alumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id_alumno"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("carrera")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("rut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("id_alumno");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("gestion_inventario.Models.Prestamo", b =>
                {
                    b.Property<long>("id_prestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id_prestamo"));

                    b.Property<bool>("entregado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_plazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_persona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("personaNavigationid_alumno")
                        .HasColumnType("bigint");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_prestamo");

                    b.HasIndex("personaNavigationid_alumno");

                    b.ToTable("prestamos");
                });

            modelBuilder.Entity("gestion_inventario.Models.PrestamoDetalle", b =>
                {
                    b.Property<long>("id_prestamo_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id_prestamo_detalle"));

                    b.Property<long>("id_inventario")
                        .HasColumnType("bigint");

                    b.Property<long>("id_prestamo")
                        .HasColumnType("bigint");

                    b.Property<long>("inventarioNavigationid_inventario")
                        .HasColumnType("bigint");

                    b.Property<long>("prestamoNavigationid_prestamo")
                        .HasColumnType("bigint");

                    b.HasKey("id_prestamo_detalle");

                    b.HasIndex("inventarioNavigationid_inventario");

                    b.HasIndex("prestamoNavigationid_prestamo");

                    b.ToTable("prestamo_detalles");
                });

            modelBuilder.Entity("gestion_inventario.Models.Producto", b =>
                {
                    b.Property<int>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_producto"));

                    b.Property<int>("ProveedorNavigationid_proveedor")
                        .HasColumnType("int");

                    b.Property<int>("categoriaNavigationid_categoria")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_categoria")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("id_proveedor")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("id_tipo_producto")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)");

                    b.Property<string>("nombre_producto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_producto");

                    b.HasIndex("ProveedorNavigationid_proveedor");

                    b.HasIndex("categoriaNavigationid_categoria");

                    b.HasIndex("id_tipo_producto");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("gestion_inventario.Models.Proveedor", b =>
                {
                    b.Property<int>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_proveedor"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_proveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("id_proveedor");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("gestion_inventario.Models.TipoProducto", b =>
                {
                    b.Property<int>("id_tipo_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_producto"));

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_tipo_producto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("id_tipo_producto");

                    b.ToTable("tipos_producto");
                });

            modelBuilder.Entity("gestion_inventario.Models.HistoricoMovimiento", b =>
                {
                    b.HasOne("gestion_inventario.Models.Inventario", "inventarioNavigation")
                        .WithMany()
                        .HasForeignKey("inventarioNavigationid_inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestion_inventario.Models.MovimientoTipo", "movimientoTipoNavigation")
                        .WithMany()
                        .HasForeignKey("movimientoTipoNavigationid_movimiento_tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inventarioNavigation");

                    b.Navigation("movimientoTipoNavigation");
                });

            modelBuilder.Entity("gestion_inventario.Models.Inventario", b =>
                {
                    b.HasOne("gestion_inventario.Models.InventarioEstado", "InventarioEstadoNavigation")
                        .WithMany()
                        .HasForeignKey("InventarioEstadoNavigationid_inventario_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestion_inventario.Models.Bodega", "bodegaNavigation")
                        .WithMany()
                        .HasForeignKey("bodegaNavigationid_bodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestion_inventario.Models.Producto", "productoNavigation")
                        .WithMany()
                        .HasForeignKey("productoNavigationid_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventarioEstadoNavigation");

                    b.Navigation("bodegaNavigation");

                    b.Navigation("productoNavigation");
                });

            modelBuilder.Entity("gestion_inventario.Models.Prestamo", b =>
                {
                    b.HasOne("gestion_inventario.Models.Persona", "personaNavigation")
                        .WithMany()
                        .HasForeignKey("personaNavigationid_alumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personaNavigation");
                });

            modelBuilder.Entity("gestion_inventario.Models.PrestamoDetalle", b =>
                {
                    b.HasOne("gestion_inventario.Models.Inventario", "inventarioNavigation")
                        .WithMany()
                        .HasForeignKey("inventarioNavigationid_inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestion_inventario.Models.Prestamo", "prestamoNavigation")
                        .WithMany()
                        .HasForeignKey("prestamoNavigationid_prestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inventarioNavigation");

                    b.Navigation("prestamoNavigation");
                });

            modelBuilder.Entity("gestion_inventario.Models.Producto", b =>
                {
                    b.HasOne("gestion_inventario.Models.Proveedor", "ProveedorNavigation")
                        .WithMany()
                        .HasForeignKey("ProveedorNavigationid_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestion_inventario.Models.Categoria", "categoriaNavigation")
                        .WithMany()
                        .HasForeignKey("categoriaNavigationid_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestion_inventario.Models.TipoProducto", "tipoProductoNavigation")
                        .WithMany("productos")
                        .HasForeignKey("id_tipo_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProveedorNavigation");

                    b.Navigation("categoriaNavigation");

                    b.Navigation("tipoProductoNavigation");
                });

            modelBuilder.Entity("gestion_inventario.Models.TipoProducto", b =>
                {
                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
