# Generated by Django 4.2.5 on 2023-09-08 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 933899)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_plazo',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 21, 19, 7, 933899)),
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table='Prestamo',
        ),
        migrations.AlterModelTable(
            name='prestamo_detalle',
            table='Prestamo_detalle',
        ),
    ]
