# Generated by Django 4.2.5 on 2023-09-10 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_prestamo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 269370)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_plazo',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 12, 46, 46, 269370)),
        ),
    ]
