# Generated by Django 4.2.5 on 2023-09-10 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('prestamos', '0003_alter_prestamo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 639477)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_plazo',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 13, 1, 13, 639477)),
        ),
    ]
