# Generated by Django 4.2.5 on 2023-09-10 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_fecha_actualizacion_and_more'),
        ('prestamos', '0004_prestamo_persona_alter_prestamo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 375522)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_plazo',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 13, 2, 44, 375522)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
