# Generated by Django 4.2.5 on 2023-09-08 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 918907)),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 918907)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 924904)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 924904)),
        ),
        migrations.AlterField(
            model_name='historico_movimiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 925906)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 919906)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 919906)),
        ),
        migrations.AlterField(
            model_name='movimiento_tipo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 926905)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 922907)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 922907)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 923907)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 19, 7, 923907)),
        ),
        migrations.AlterModelTable(
            name='bodega',
            table='Bodega',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
        migrations.AlterModelTable(
            name='historico_movimiento',
            table='Historico_movimiento',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='Inventario',
        ),
        migrations.AlterModelTable(
            name='inventario_estado',
            table='Inventario_estado',
        ),
        migrations.AlterModelTable(
            name='movimiento_tipo',
            table='Movimiento_tipo',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedor',
        ),
        migrations.AlterModelTable(
            name='tipo_producto',
            table='Tipo_producto',
        ),
    ]
