# Generated by Django 4.2.5 on 2023-09-10 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_bodega_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 261663)),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 261663)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 265675)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 265675)),
        ),
        migrations.AlterField(
            model_name='historico_movimiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 266675)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 262678)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 262678)),
        ),
        migrations.AlterField(
            model_name='movimiento_tipo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 267675)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 263676)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 263676)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 264676)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 46, 46, 264676)),
        ),
    ]
