# Generated by Django 4.2.5 on 2023-09-10 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_bodega_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 625481)),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 625481)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 629498)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 629498)),
        ),
        migrations.AlterField(
            model_name='historico_movimiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 630498)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 626501)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 626501)),
        ),
        migrations.AlterField(
            model_name='movimiento_tipo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 631497)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 627500)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 627500)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 628499)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 628499)),
        ),
    ]
