# Generated by Django 4.2.5 on 2023-09-10 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_bodega_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 358532)),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 358532)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 362526)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 362526)),
        ),
        migrations.AlterField(
            model_name='historico_movimiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 363526)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 359528)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 359528)),
        ),
        migrations.AlterField(
            model_name='movimiento_tipo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 364525)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 360527)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 360527)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 361527)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 361527)),
        ),
    ]
