# Generated by Django 4.2.5 on 2023-09-08 00:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 522296))),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 522296))),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 526310))),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 526310))),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_estado',
            fields=[
                ('id_estado_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_inventario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_tipo',
            fields=[
                ('id_tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_movimiento', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 528308))),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=90)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 525311))),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 525311))),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_producto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 524292))),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 524292))),
                ('marca', models.CharField(max_length=90)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
                ('proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor')),
                ('tipo_producto', models.ForeignKey(db_column='id_tipo_producto', on_delete=django.db.models.deletion.PROTECT, to='inventario.tipo_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 523293))),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 523293))),
                ('bodega', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('estado_inventario', models.ForeignKey(db_column='id_estado_inventario', on_delete=django.db.models.deletion.PROTECT, to='inventario.inventario_estado')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_movimiento',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('comentarios', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 21, 15, 32, 527309))),
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.PROTECT, to='inventario.inventario')),
                ('tipo_movimiento', models.ForeignKey(db_column='id_tipo_movimiento', on_delete=django.db.models.deletion.PROTECT, to='inventario.movimiento_tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
