# Generated by Django 4.2.5 on 2023-09-10 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 373525)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 2, 44, 373525)),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
