# Generated by Django 4.2.5 on 2023-09-10 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_alumno', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_alumno', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 637479))),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 1, 13, 637479))),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('estado', models.CharField(max_length=30)),
                ('carrera', models.CharField(max_length=70)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
